package dev.abros.anthub.core;
import com.google.gson.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
@Tag("postgres") class CommunityTasksTest {
 @TempDir Path temp;PgDatabase db;CommunityStore store;CommunityStore.Actor owner,other;
 @BeforeEach void start()throws Exception{db=TestDatabase.database(temp);store=new CommunityStore(db,CommunityStore.defaults());owner=new CommunityStore.Actor(UUID.randomUUID().toString(),"Owner",false,false);other=new CommunityStore.Actor(UUID.randomUUID().toString(),"Other",true,true);store.seen(owner);store.seen(other);}
 JsonObject input(String op){var j=new JsonObject();j.addProperty("section","home");j.addProperty("op",op);return j;}
 JsonObject create()throws Exception{var q=input("workSave");q.addProperty("title","Build");q.addProperty("description","Work");q.addProperty("operationId",UUID.randomUUID().toString());q.addProperty("issuedAt",System.currentTimeMillis());var first=store.request(owner,q);assertEquals(first.get("task"),store.request(owner,q).get("task"));return first.getAsJsonObject("task");}
 JsonObject command(JsonObject t,String op){var q=input(op);q.addProperty("task",Json.str(t,"id"));q.add("revision",t.get("revision"));return q;}
 @Test void personalTasksArePrivateAndCodesSurviveRename()throws Exception{var t=create();String code=Json.str(t,"code");assertFalse(code.contains("-"));assertThrows(CommunityFailure.class,()->store.request(other,command(t,"workGet")));var q=command(t,"workSave");q.addProperty("title","Renamed");q.addProperty("description","");var renamed=store.request(owner,q).getAsJsonObject("task");assertEquals(code,Json.str(renamed,"code"));assertThrows(CommunityFailure.class,()->store.request(owner,q));assertEquals(1,store.request(owner,input("workList")).getAsJsonArray("tasks").size());}
 @Test void stockNeedsOwnerAndInventoryCannotBeCountedTwice()throws Exception{var t=create();String code=Json.str(t,"code");var tasks=new CommunityTasks(db,store);var stock=new JsonObject();stock.addProperty("inventory","chest:1");stock.addProperty("at",10);var items=new JsonObject();items.addProperty("minecraft:stone",64);stock.add("items",items);assertThrows(CommunityFailure.class,()->tasks.bind(other,"Owner",code,"sign:1",stock));tasks.bind(owner,"Owner",code,"sign:1",stock);assertThrows(CommunityFailure.class,()->tasks.bind(owner,"Owner",code,"sign:2",stock));tasks.bind(owner,"Owner",code,"sign:1",stock);var q=command(t,"workResources");var resources=new JsonArray();var need=new JsonObject();need.addProperty("item","minecraft:stone");need.addProperty("amount",100);resources.add(need);q.add("resources",resources);t=store.request(owner,q).getAsJsonObject("task");assertEquals(64,t.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());tasks.stock("sign:1",new JsonObject(),true);assertEquals(0,tasks.bindings().size());}
 @Test void commentHistoryDoesNotOverflowPacketAndSubtasksPersist()throws Exception{var t=create();for(int n=0;n<40;n++){var q=command(t,"workComment");q.addProperty("text","x".repeat(500));t=store.request(owner,q).getAsJsonObject("task");}assertEquals(40,t.get("commentCount").getAsInt());assertEquals(20,t.getAsJsonArray("comments").size());assertTrue(t.toString().length()<32767);var q=command(t,"workSubtask");q.addProperty("title","First stage");t=store.request(owner,q).getAsJsonObject("task");q=command(t,"workSubtask");q.addProperty("index",0);assertTrue(store.request(owner,q).getAsJsonObject("task").getAsJsonArray("subtasks").get(0).getAsJsonObject().get("done").getAsBoolean());}
 @Test void mergedInventoriesAreCountedOnlyOnceAcrossTasks()throws Exception{var first=create();var second=create();var tasks=new CommunityTasks(db,store);var stock=new JsonObject();stock.addProperty("inventory","chest:b");stock.addProperty("at",100);var items=new JsonObject();items.addProperty("minecraft:stone",64);stock.add("items",items);tasks.bind(owner,"Owner",Json.str(second,"code"),"sign:b",stock);stock.addProperty("inventory","chest:a");tasks.bind(owner,"Owner",Json.str(first,"code"),"sign:a",stock);for(var t:List.of(first,second)){var q=command(t,"workResources");var resources=new JsonArray();var need=new JsonObject();need.addProperty("item","minecraft:stone");need.addProperty("amount",100);resources.add(need);q.add("resources",resources);store.request(owner,q);}stock.addProperty("inventory","merged");tasks.stock("sign:b",stock,false);tasks.stock("sign:a",stock,false);var a=store.request(owner,command(first,"workGet")).getAsJsonObject("task");var b=store.request(owner,command(second,"workGet")).getAsJsonObject("task");assertEquals(64,a.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());assertEquals(0,b.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());tasks.stock("sign:a",new JsonObject(),true);tasks.stock("sign:b",stock,false);b=store.request(owner,command(second,"workGet")).getAsJsonObject("task");assertEquals(64,b.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());}
 @Test void globalSearchDoesNotRevealAnotherPlayersPersonalTasks()throws Exception{var task=create();var q=input("globalSearch");q.addProperty("query","Build");assertTrue(store.request(owner,q).getAsJsonArray("entries").asList().stream().anyMatch(e->Json.opt(e.getAsJsonObject(),"id","").equals(Json.str(task,"id"))));assertFalse(store.request(other,q).getAsJsonArray("entries").asList().stream().anyMatch(e->Json.opt(e.getAsJsonObject(),"id","").equals(Json.str(task,"id"))));}
 @Test void listFiltersBeforePaginationAndKeepsTaskDetailsPrivate()throws Exception{
  var first=create();var second=create();var change=command(second,"workSave");change.addProperty("title","Bridge");change.addProperty("description","Need glass");second=store.request(owner,change).getAsJsonObject("task");var working=command(second,"workStatus");working.addProperty("status","working");second=store.request(owner,working).getAsJsonObject("task");var stage=command(second,"workSubtask");stage.addProperty("title","Foundations");second=store.request(owner,stage).getAsJsonObject("task");stage=command(second,"workSubtask");stage.addProperty("index",0);store.request(owner,stage);
  var query=input("workList");query.addProperty("query","GLASS");query.addProperty("status","working");var rows=store.request(owner,query).getAsJsonArray("tasks");assertEquals(1,rows.size());var result=rows.get(0).getAsJsonObject();assertEquals(Json.str(second,"id"),Json.str(result,"id"));assertEquals(1,result.get("stagesDone").getAsInt());assertEquals(1,result.get("stagesTotal").getAsInt());assertFalse(result.has("comments"));assertFalse(result.has("stocks"));assertEquals(0,store.request(other,query).getAsJsonArray("tasks").size());query.addProperty("query",Json.str(second,"code"));assertEquals(1,store.request(owner,query).getAsJsonArray("tasks").size());query.addProperty("status","done");assertTrue(store.request(owner,query).getAsJsonArray("tasks").isEmpty());query.addProperty("status","invalid");assertThrows(IllegalArgumentException.class,()->store.request(owner,query));
 }

}
