package dev.abros.anthub.core;
import com.google.gson.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
@org.junit.jupiter.api.Tag("postgres")
class CommunityStoreTest {
 @TempDir Path world;CommunityStore db;
 CommunityStore.Actor owner=actor("Owner",false),alice=actor("Alice",false),bob=actor("Bob",false),admin=actor("Admin",true);
 static CommunityStore.Actor actor(String name,boolean admin){return new CommunityStore.Actor(UUID.randomUUID().toString(),name,admin,admin);}
 @BeforeEach void start()throws Exception{db=new CommunityStore(TestDatabase.database(world),CommunityStore.defaults());for(var a:List.of(owner,alice,bob,admin))db.seen(a);}
 @AfterEach void close()throws Exception{db.close();}
 JsonObject input(String section,String op,String id){var j=new JsonObject();j.addProperty("section",section);j.addProperty("op",op);j.addProperty("id",id);return j;}
 JsonObject create(String section)throws Exception{var j=input(section,"create","");j.addProperty("title","Example");j.addProperty("description","Description");j.addProperty("days",14);j.addProperty("type","Команда");j.addProperty("startsAt",Instant.now().plusSeconds(120).toString());j.addProperty("endsAt",Instant.now().plusSeconds(60).toString());j.addProperty("capacity",1);var options=new JsonArray();options.add("One");options.add("Two");j.add("options",options);return db.request(Set.of("events","polls").contains(section)?admin:owner,j).getAsJsonObject("detail");}
 String id(JsonObject j){return Json.str(j,"id");}
 JsonObject detail(String section,String id,CommunityStore.Actor a)throws Exception{return db.request(a,input(section,"detail",id)).getAsJsonObject("detail");}
 @Test void boardHasNoCategoriesAndManyPrivateResponses()throws Exception{assertTrue(db.configuration().getAsJsonArray("categories").isEmpty());var post=create("board");for(var a:List.of(alice,bob)){var reply=input("board","respond",id(post));reply.addProperty("text","Private "+a.name());db.request(a,reply);}assertEquals(2,detail("board",id(post),owner).getAsJsonObject("responses").size());var view=detail("board",id(post),alice).getAsJsonObject("responses");assertEquals(1,view.size());assertFalse(view.has(bob.id()));for(var a:List.of(alice,bob)){var accept=input("board","respondDecision",id(post));accept.addProperty("target",a.id());accept.addProperty("decision","accepted");accept.addProperty("text","Welcome");db.request(owner,accept);assertEquals("accepted",Json.str(detail("board",id(post),a).getAsJsonObject("responses").getAsJsonObject(a.id()),"status"));assertEquals(1,db.unread(a.id()));}}
 @Test void unauthorizedChangesRollBack()throws Exception{var p=create("board");assertThrows(IllegalArgumentException.class,()->db.request(alice,input("board","close",id(p))));assertEquals("open",Json.str(detail("board",id(p),owner),"status"));assertThrows(IllegalArgumentException.class,()->db.request(alice,input("ideas","detail",id(p))));assertEquals(0,db.unread(owner.id()));}
 @Test void duplicateResponseDoesNotDuplicateNotice()throws Exception{var p=create("board");var q=input("board","respond",id(p));q.addProperty("text","Hello");db.request(alice,q);assertThrows(IllegalArgumentException.class,()->db.request(alice,q));assertEquals(1,db.unread(owner.id()));}
 @Test void disablingASectionBlocksRequests()throws Exception{var p=create("board");var c=db.configuration();c.getAsJsonArray("sections").remove(new JsonPrimitive("board"));db.configure(c);assertThrows(IllegalArgumentException.class,()->detail("board",id(p),owner));}
 @Test void pollVotesArePrivateAndUnique()throws Exception{var p=create("polls");var q=input("polls","vote",id(p));var choices=new JsonArray();choices.add(0);q.add("choices",choices);var view=db.request(alice,q).getAsJsonObject("detail");assertFalse(view.has("votes"));assertEquals(-1,view.getAsJsonArray("counts").get(0).getAsInt());assertThrows(IllegalArgumentException.class,()->db.request(alice,q));assertFalse(detail("polls",id(p),bob).get("voted").getAsBoolean());}
 @Test void waitlistPromotionAndReminderArePersistent()throws Exception{var p=create("events");db.request(alice,input("events","join",id(p)));db.request(bob,input("events","join",id(p)));db.request(alice,input("events","leave",id(p)));assertEquals(1,db.unread(bob.id()));db.reminders(System.currentTimeMillis());int n=db.unread(bob.id());db.reminders(System.currentTimeMillis());assertEquals(n,db.unread(bob.id()));db.close();db=new CommunityStore(TestDatabase.database(world),CommunityStore.defaults());assertTrue(detail("events",id(p),bob).get("isParticipant").getAsBoolean());}
 @Test void groupMembershipRequiresAcceptanceAndLeaderCannotLeave()throws Exception{var p=create("groups");var q=input("groups","apply",id(p));q.addProperty("text","Join please");db.request(alice,q);assertFalse(detail("groups",id(p),alice).get("isMember").getAsBoolean());var accept=input("groups","application",id(p));accept.addProperty("target",alice.id());accept.addProperty("accept",true);assertThrows(IllegalArgumentException.class,()->db.request(bob,accept));db.request(owner,accept);assertTrue(detail("groups",id(p),alice).get("isMember").getAsBoolean());assertThrows(IllegalArgumentException.class,()->db.request(owner,input("groups","leave",id(p))));}
 @Test void nonAdminCannotCreatePollsOrEvents()throws Exception{for(String section:List.of("polls","events")){var q=input(section,"create","");q.addProperty("title","Bad");q.addProperty("description","Bad");assertThrows(IllegalArgumentException.class,()->db.request(alice,q));}}
 @Test void proposalStatusRequiresAdminAndNotifiesAuthor()throws Exception{var p=create("ideas");var q=input("ideas","status",id(p));q.addProperty("status","planned");q.addProperty("text","Next month");assertThrows(IllegalArgumentException.class,()->db.request(alice,q));db.request(admin,q);assertEquals(1,db.unread(owner.id()));assertEquals("planned",Json.str(detail("ideas",id(p),owner),"status"));}
 @Test void notificationsBelongToRecipient()throws Exception{db.externalNotice(alice.id(),"Private");assertEquals(1,db.request(alice,input("notifications","list","")).getAsJsonArray("entries").size());assertTrue(db.request(bob,input("notifications","list","")).getAsJsonArray("entries").isEmpty());db.request(bob,input("notifications","read",""));assertEquals(1,db.unread(alice.id()));db.request(alice,input("notifications","read",""));assertEquals(0,db.unread(alice.id()));}
 @Test void reportsUseDatabaseAndNotifyOnReply()throws Exception{var reports=new CommunityReports(db);var q=new JsonObject();q.addProperty("message","Help");String ticket=reports.submit(UUID.fromString(alice.id()),"Alice",q,System.currentTimeMillis());reports.reply(ticket,"Admin","Fixed",true);assertEquals(1,db.unread(alice.id()));assertTrue(reports.list(UUID.fromString(bob.id()),0).isEmpty());assertFalse(Files.exists(world.resolve("anthub/reports")));}
 @Test void playerSearchAndAuditAreInDatabase()throws Exception{assertEquals(1,db.people("ali",0).size());db.audit("Admin","test","done");assertEquals(1,db.records("audit").size());assertFalse(Files.exists(world.resolve("anthub/server.db")));assertFalse(Files.exists(world.resolve("anthub/admin-log.json")));}

 @Test void cancelledWaiterDoesNotPromoteAnAlreadyAdmittedPlayer()throws Exception{var p=create("events");db.request(alice,input("events","join",id(p)));db.request(bob,input("events","join",id(p)));db.request(bob,input("events","leave",id(p)));assertEquals(0,db.unread(alice.id()));}
 @Test void popupPreferencesDoNotDeleteNotifications()throws Exception{var q=input("home","preferences","");var prefs=new JsonObject();prefs.add("favorites",new JsonArray());var muted=new JsonArray();muted.add("ideas");prefs.add("muted",muted);q.add("preferences",prefs);db.request(owner,q);var p=create("ideas");var status=input("ideas","status",id(p));status.addProperty("status","planned");status.addProperty("text","Soon");db.request(admin,status);assertEquals(1,db.unread(owner.id()));assertEquals(0,db.popupSequence(owner.id()));var summary=db.notificationSummary(List.of(UUID.fromString(owner.id()))).get(UUID.fromString(owner.id()));assertEquals(1,summary.unread());assertEquals(0,summary.sequence());}
 @Test void disabledSectionCannotBeReadThroughAnotherSection()throws Exception{var p=create("board");var config=db.configuration();config.getAsJsonArray("sections").remove(new JsonPrimitive("board"));db.configure(config);assertThrows(IllegalArgumentException.class,()->db.request(owner,input("ideas","detail",id(p))));}
 @Test void repliesArePagedAndCannotExceedPacketBudget()throws Exception{var p=create("board");for(int i=0;i<15;i++){var a=actor("User"+i,false);var q=input("board","respond",id(p));q.addProperty("text","x".repeat(1000));db.request(a,q);}var response=db.request(owner,input("board","detail",id(p)));assertEquals(5,response.getAsJsonObject("detail").getAsJsonObject("responses").size());assertTrue(Json.GSON.toJson(response).length()<32767);}
 @Test void groupMembershipLimitIsEnforcedOnInvitation()throws Exception{var config=db.configuration();config.addProperty("maxMemberships",1);db.configure(config);var first=create("groups");var secondInput=input("groups","create","");secondInput.addProperty("title","Second");secondInput.addProperty("description","Different");secondInput.addProperty("type","Команда");var second=db.request(bob,secondInput).getAsJsonObject("detail");for(var group:List.of(first,second)){var who=id(group).equals(id(first))?owner:bob;var invite=input("groups","invite",id(group));invite.addProperty("target",alice.id());db.request(who,invite);}var accept=input("groups","invitation",id(first));accept.addProperty("accept",true);db.request(alice,accept);accept.addProperty("id",id(second));assertThrows(IllegalArgumentException.class,()->db.request(alice,accept));assertTrue(detail("groups",id(second),alice).getAsJsonObject("invitations").has(alice.id()));}
 @Test void failedTransactionRollsBackAllWrites()throws Exception{assertThrows(Exception.class,()->db.transaction(()->{db.record("test","one",new JsonObject());throw new Exception("stop");}));assertNull(db.record("test","one"));}
}
