package dev.abros.anthub.client;
import com.google.gson.*;
import dev.abros.anthub.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
final class AdminDashboardScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final RequestSession session=new RequestSession();private JsonObject data=new JsonObject();private boolean busy,loaded,technical;private String notice="";private Button refresh;
 AdminDashboardScreen(Screen parent){this(parent,false);}
 AdminDashboardScreen(Screen parent,boolean technical){super(Component.literal(technical?"Диагностика AntHub":"Сводка обращений"));this.parent=parent;this.technical=technical;}
 private final java.util.List<String> lines=new java.util.ArrayList<>();
 private int top(){return DialogPanel.top(height,340);}private int bottom(){return height-top();}private int w(){return Math.min(440,width-32);}private int x(){return (width-w())/2;}
 private void load(){if(busy)return;var j=new JsonObject();j.addProperty("action","adminDashboard");busy=true;if(refresh!=null)refresh.active=false;notice="Обновляем сводку…";ServerMenuClient.request(session.begin(j,false,System.currentTimeMillis()));}
 @Override protected void init(){lines.clear();if(Json.opt(ServerMenuClient.moderationVote,"status","").equals("open"))lines.add("Идёт голосование о наказании");for(String key:java.util.List.of("restartAt","maintenanceUntil"))if(data.has(key)&&data.get(key).getAsLong()>System.currentTimeMillis())lines.add((key.equals("restartAt")?"Перезапуск через ":"Обслуживание ещё ")+Math.max(1,(data.get(key).getAsLong()-System.currentTimeMillis())/60000)+" мин.");if(technical&&data.has("retention")){var retention=data.getAsJsonObject("retention");lines.add("Плановая очистка · количество записей");lines.add("Обращения: "+retention.get("reports")+" · Корзина: "+retention.get("trash")+" · Журнал: "+retention.get("audit"));}if(technical&&data.has("recentErrors")){var errors=data.getAsJsonArray("recentErrors");lines.add("Последние ошибки: "+errors.size());for(var error:errors){var e=error.getAsJsonObject();String text=Json.opt(e,"operation","")+" · "+Json.opt(e,"type","");for(var line:font.getSplitter().splitLines(text,w()-16,net.minecraft.network.chat.Style.EMPTY))lines.add(line.getString());}}if(lines.isEmpty())lines.add(technical?"Нет дополнительных данных":"Назначьте ответственного → ответьте игроку → закройте обращение.");scrollArea(lines.size(),top()+(technical?104:156),bottom()-66,18,x()+w()+4);if(!technical){addRenderableWidget(Button.builder(Component.literal("Очередь обращений"),b->FeatureListScreen.open(this,"reports")).bounds(x()+8,top()+104,148,20).build()).active=ServerMenuClient.may("anthub.reports");addRenderableWidget(Button.builder(Component.literal("Технические данные ▾"),b->minecraft.setScreen(new ChoicePopup(this,"Содержимое сводки",java.util.List.of("Главное","Технические данные"),n->{technical=n==1;resetScroll();rebuildWidgets();},b).current(technical?1:0))).bounds(x()+8,top()+130,148,20).build());}refresh=addRenderableWidget(Button.builder(Component.literal("Обновить"),b->load()).bounds(x()+8,bottom()-28,90,20).build());refresh.active=!busy;addRenderableWidget(Button.builder(Component.literal("Назад"),b->onClose()).bounds(x()+w()-88,bottom()-28,80,20).build());if(!loaded){loaded=true;load();}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("error"))notice=Json.opt(j,"text","Нет данных");else{notice="";boolean changed=!UiPayload.same(data,j);data=j.deepCopy();if(!changed){if(refresh!=null)refresh.active=true;return;}}rebuildWidgets();}
 @Override public void tick(){if(!ServerMenuClient.admin()){onClose();return;}if(session.timeout(System.currentTimeMillis())){busy=false;notice="Нет ответа. Обновите данные.";rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);DialogPanel.draw(g,width,w(),top(),bottom());}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());String[] keys=technical?new String[]{"recentErrors","storageQueue","readQueue"}:new String[]{"openReports","unassignedReports","highReports"},labels=technical?new String[]{"Последние ошибки","Очередь записи","Очередь чтения"}:new String[]{"Открыты","Без ответственного","Высокий приоритет"};int tile=(w()-24)/3;for(int i=0;i<3;i++){int left=x()+8+i*(tile+4);UiKit.surface(g,left,top()+38,tile,56,UiKit.surface());g.drawString(font,UiKit.fit(font,labels[i],tile-12),left+6,top()+46,UiKit.muted(),false);g.drawString(font,data.has(keys[i])?keys[i].equals("recentErrors")?Integer.toString(data.getAsJsonArray(keys[i]).size()):data.get(keys[i]).getAsString():"…",left+6,top()+66,i==2?UiPalette.color(0xFFEF7777):UiKit.accent(),false);}for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++)g.drawString(font,lines.get(n),x()+8,top()+(technical?104:156)+(n-firstRow)*18,UiPalette.color(0xD7E2EC));Ui.status(g,font,notice,x()+8,bottom()-60,w()-16,bottom()-34);}
 @Override public void onClose(){session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
