package dev.abros.anthub.client;

import com.google.gson.*;
import dev.abros.anthub.core.Json;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.function.*;

    final class CommunityForm extends ScrollScreen implements CommunityScreen.Receiver {
        private final CommunityScreen parent;private final List<CommunityScreen.Field> fields;private final JsonObject values;private final Consumer<JsonObject> submit;private boolean busy;private String request="",error="";private long sentAt;private final String draftKey;private final String server,account;private final dev.abros.anthub.core.DraftStore drafts;private long saveAt;private final dev.abros.anthub.core.RequestSession session=new dev.abros.anthub.core.RequestSession();private JsonObject lastValues;private boolean retryable,conflict,refreshing;private JsonObject recovered;private boolean uncertain;
        private void persist(){var fieldsOnly=new JsonObject();for(var f:fields)if(values.has(f.key()))fieldsOnly.add(f.key(),values.get(f.key()).deepCopy());if(values.has("location"))fieldsOnly.add("location",values.get("location").deepCopy());saveAt=0;Client.IO.submit(()->{try{drafts.save(server,account,draftKey,fieldsOnly);}catch(Exception ex){net.minecraft.client.Minecraft.getInstance().execute(()->error="Не удалось сохранить черновик");}});}
        private void changed(){saveAt=System.currentTimeMillis()+800;retryable=false;}

        CommunityForm(CommunityScreen parent,String title,List<CommunityScreen.Field> fields,JsonObject preset,Consumer<JsonObject> submit){super(Component.literal(title));this.parent=parent;this.fields=fields;var identity=preset.deepCopy();identity.remove("revision");draftKey=parent.section+"|"+parent.itemId+"|"+title+"|"+identity.toString();var mc=net.minecraft.client.Minecraft.getInstance();server=mc.getCurrentServer()==null?"":mc.getCurrentServer().ip;account=Json.opt(ServerMenuClient.state,"uuid","");drafts=new dev.abros.anthub.core.DraftStore(mc.gameDirectory.toPath().resolve("anthub/drafts"));values=preset.deepCopy();try{var saved=drafts.load(server,account,draftKey);for(var field:fields)if(saved.has(field.key()))values.add(field.key(),saved.get(field.key()));if(saved.has("location"))values.add("location",saved.get("location"));}catch(Exception ex){error="Черновик недоступен";}try{recovered=drafts.pending(server,account,draftKey);if(recovered!=null){uncertain=true;retryable=true;error="Предыдущая отправка не подтверждена. Проверьте её безопасным повтором.";}}catch(Exception ex){error="Не удалось проверить предыдущую отправку";}this.submit=submit;}
        @Override protected void init(){int w=Math.min(600,width-40),x=(width-w)/2;scrollArea(fields.size(),38,height-100,66,x+w+4);for(int n=firstRow;n<Math.min(fields.size(),firstRow+visibleRows);n++){CommunityScreen.Field f=fields.get(n);int y=38+(n-firstRow)*66;if(f.options()!=null){if(!values.has(f.key()))values.addProperty(f.key(),CommunityScreen.optionValue(f.options().get(0)));addRenderableWidget(Button.builder(Component.literal(f.options().asList().stream().filter(o->CommunityScreen.optionValue(o).equals(Json.str(values,f.key()))).map(CommunityScreen::optionLabel).findFirst().orElse("")),b->{int i=0;for(;i<f.options().size();i++)if(CommunityScreen.optionValue(f.options().get(i)).equals(Json.str(values,f.key())))break;values.addProperty(f.key(),CommunityScreen.optionValue(f.options().get((i+1)%f.options().size())));b.setMessage(Component.literal(CommunityScreen.optionLabel(f.options().get((i+1)%f.options().size()))));changed();}).bounds(x,y+15,w,20).build());}else if(Set.of("description","text","options").contains(f.key())){var edit=addRenderableWidget(new MultiLineEditBox(font,x,y+15,w,40,Component.literal(f.label()),Component.literal(f.label())));edit.setCharacterLimit(f.limit());edit.setValue(Json.opt(values,f.key(),""));edit.setValueListener(v->{values.addProperty(f.key(),v);changed();});}else{var edit=addRenderableWidget(new EditBox(font,x,y+15,w,20,Component.literal(f.label())));edit.setMaxLength(f.limit());edit.setValue(Json.opt(values,f.key(),""));edit.setResponder(v->{values.addProperty(f.key(),v);changed();});}}
            if(fields.stream().anyMatch(f->f.key().equals("title"))||title.getString().equals("Место"))addRenderableWidget(Button.builder(Component.literal(values.has("location")&&!values.get("location").isJsonNull()?"Изменить место…":"Добавить место (необязательно)…"),b->minecraft.setScreen(new LocationEditor(this,values.get("location"),parent.section.equals("groups")||!Json.opt(values,"group","").isEmpty()||parent.data.has("detail")&&parent.data.getAsJsonObject("detail").has("group"),location->{values.add("location",location);changed();}))).bounds(x,height-54,w,20).build());
            if(conflict)addRenderableWidget(Button.builder(Component.literal("Обновить запись, сохранив текст"),b->{if(busy)return;var q=new JsonObject();q.addProperty("action","community");q.addProperty("op","detail");q.addProperty("section",parent.section);q.addProperty("id",parent.itemId);q=session.begin(q,false,System.currentTimeMillis());request=Json.str(q,"request");busy=true;refreshing=true;ServerMenuClient.request(q);}).bounds(x,height-88,w,20).build());
            for(var widget:renderables)if(widget instanceof AbstractWidget input)input.active=!busy&&!uncertain;
            var save=addRenderableWidget(Button.builder(Component.literal(busy?"Отправка…":retryable?"Повторить":"Отправить"),b->send()).bounds(x,height-28,w/2-3,20).build());save.active=!busy&&!conflict;addRenderableWidget(Button.builder(Component.literal("Назад"),b->onClose()).bounds(x+w/2+3,height-28,w/2-3,20).build());}
        private void send(){if(busy)return;var body=values.deepCopy();try{if(recovered!=null){body=session.begin(recovered,true,System.currentTimeMillis());recovered=null;lastValues=values.deepCopy();dispatch(body);return;}for(var f:fields){String value=Json.opt(values,f.key(),"").strip();if(value.isBlank()&&!Set.of("group","category").contains(f.key()))throw new IllegalArgumentException("Заполните: "+f.label());if(Set.of("days","capacity").contains(f.key()))body.addProperty(f.key(),Integer.parseInt(value));if(Set.of("startsAt","endsAt").contains(f.key()))body.addProperty(f.key(),LocalDateTime.parse(value,DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm").withResolverStyle(java.time.format.ResolverStyle.STRICT)).atZone(ZoneId.systemDefault()).toInstant().toString());if(f.key().equals("options")){var options=new JsonArray();for(String s:value.split("\\|"))options.add(s.strip());body.add("options",options);}if(Set.of("multiple","changeVote","liveResults").contains(f.key()))body.addProperty(f.key(),value.equals("Да"));}if(retryable&&lastValues!=null&&lastValues.equals(values)){body=session.retry(System.currentTimeMillis());}else{lastValues=values.deepCopy();body=session.begin(body,true,System.currentTimeMillis());}dispatch(body);}catch(Exception ex){error="Проверьте поля: "+ex.getMessage();}}
        private void dispatch(JsonObject body){request=Json.str(body,"request");persist();busy=true;uncertain=true;sentAt=System.currentTimeMillis();error="";var pending=session.command();Client.IO.submit(()->{try{drafts.pending(server,account,draftKey,pending);net.minecraft.client.Minecraft.getInstance().execute(()->{submit.accept(body);});}catch(Exception ex){net.minecraft.client.Minecraft.getInstance().execute(()->{session.cancel();busy=false;uncertain=false;error="Не удалось сохранить состояние отправки. Запрос не отправлен.";rebuildWidgets();});}});rebuildWidgets();}
        public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;uncertain=j.has("error")&&!Set.of("CONFLICT","INVALID","FORBIDDEN","EXPIRED","NOT_FOUND").contains(Json.opt(j,"code",""));if(!uncertain)Client.IO.submit(()->{try{drafts.pending(server,account,draftKey,null);}catch(Exception ignored){}});if(j.has("error")){error=Json.opt(j,"text","Ошибка");conflict=Json.opt(j,"code","").equals("CONFLICT");refreshing=false;retryable=!Set.of("CONFLICT","INVALID","FORBIDDEN","EXPIRED").contains(Json.opt(j,"code",""));rebuildWidgets();return;}if(refreshing){refreshing=false;conflict=false;retryable=false;values.add("revision",j.getAsJsonObject("detail").get("revision"));error="Данные обновлены. Проверьте свой ответ перед отправкой.";rebuildWidgets();return;}Client.IO.submit(()->{try{drafts.remove(server,account,draftKey);}catch(Exception ignored){}});saveAt=0;minecraft.setScreen(parent.surface());parent.busy=false;parent.invalidate();}
        @Override public boolean mouseScrolled(double x,double y,double dx,double dy){for(var child:children())if(child instanceof MultiLineEditBox edit&&edit.isMouseOver(x,y)&&edit.mouseScrolled(x,y,dx,dy))return true;return super.mouseScrolled(x,y,dx,dy);}
        @Override public void render(GuiGraphics g,int x,int y,float d){super.render(g,x,y,d);g.drawCenteredString(font,title,width/2,14,0xE2BE75);int left=(width-Math.min(600,width-40))/2;for(int n=firstRow;n<Math.min(fields.size(),firstRow+visibleRows);n++)g.drawString(font,fields.get(n).label(),left,38+(n-firstRow)*66,0xEEEEEE);Ui.status(g,font,error,left,height-80,width-40,height-56);}
        @Override public void onClose(){persist();session.cancel();minecraft.setScreen(parent.surface());}
        @Override public void tick(){if(saveAt>0&&System.currentTimeMillis()>=saveAt)persist();if(!ServerMenuClient.available()){persist();minecraft.setScreen(null);}else if(session.timeout(System.currentTimeMillis())){if(refreshing){refreshing=false;busy=false;conflict=true;error="Обновление не удалось. Попробуйте ещё раз.";rebuildWidgets();return;}busy=false;uncertain=true;retryable=true;error="Ответ не получен. Повтор безопасен: действие не продублируется.";rebuildWidgets();}}
        @Override public boolean isPauseScreen(){return false;}
    }
