package dev.abros.anthub.client;

import com.google.gson.*;
import dev.abros.anthub.core.Json;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.function.*;

    final class CommunityForm extends ScrollScreen implements CommunityScreen.Receiver {
        private final CommunityScreen parent;private final List<CommunityScreen.Field> fields;private final JsonObject values;private final Consumer<JsonObject> submit;private final Map<String,String> fieldErrors=new HashMap<>();private JsonObject original;private boolean busy;private String request="",error="";private long sentAt;private final String draftKey;private final String server,account;private final dev.abros.anthub.core.DraftStore drafts;private long saveAt;private final dev.abros.anthub.core.RequestSession session=new dev.abros.anthub.core.RequestSession();private JsonObject lastValues;private boolean retryable,conflict,refreshing;private JsonObject recovered;private boolean uncertain;
        private int panelTop(){return DialogPanel.top(height,Math.min(390,138+shownFields().size()*66));}
        private int panelBottom(){return height-panelTop();}
        private void persist(){var fieldsOnly=new JsonObject();for(var f:fields)if(values.has(f.key()))fieldsOnly.add(f.key(),values.get(f.key()).deepCopy());if(values.has("location"))fieldsOnly.add("location",values.get("location").deepCopy());saveAt=0;Client.IO.submit(()->{try{drafts.save(server,account,draftKey,fieldsOnly);}catch(Exception ex){net.minecraft.client.Minecraft.getInstance().execute(()->error="Не удалось сохранить черновик");}});}
        private void changed(){saveAt=System.currentTimeMillis()+800;retryable=false;}

        CommunityForm(CommunityScreen parent,String title,List<CommunityScreen.Field> fields,JsonObject preset,Consumer<JsonObject> submit){super(Component.literal(title));this.parent=parent;this.fields=fields;var identity=preset.deepCopy();identity.remove("revision");draftKey=parent.section+"|"+parent.itemId+"|"+title+"|"+identity.toString();var mc=net.minecraft.client.Minecraft.getInstance();server=mc.getCurrentServer()==null?"":mc.getCurrentServer().ip;account=Json.opt(ServerMenuClient.state,"uuid","");drafts=new dev.abros.anthub.core.DraftStore(mc.gameDirectory.toPath().resolve("anthub/drafts"));values=preset.deepCopy();original=preset.deepCopy();try{var saved=drafts.load(server,account,draftKey);for(var field:fields)if(saved.has(field.key()))values.add(field.key(),saved.get(field.key()));if(saved.has("location"))values.add("location",saved.get("location"));}catch(Exception ex){error="Черновик недоступен";}try{recovered=drafts.pending(server,account,draftKey);if(recovered!=null){uncertain=true;retryable=true;error="Предыдущая отправка не подтверждена. Проверьте её безопасным повтором.";}}catch(Exception ex){error="Не удалось проверить предыдущую отправку";}this.submit=submit;}
        private List<CommunityScreen.Field> shownFields(){return fields.stream().filter(f->switch(f.key()){case "invitees"->Json.opt(values,"visibility","public").equals("invited");case "occurrences"->!Json.opt(values,"repeat","none").equals("none");case "item","quantity","terms"->!Json.opt(values,"trade","none").equals("none");default->true;}).toList();}
        @Override public void renderBackground(GuiGraphics g,int x,int y,float d){super.renderBackground(g,x,y,d);DialogPanel.draw(g,width,Math.min(480,width-40),panelTop(),panelBottom());}
 @Override protected void init(){var fields=shownFields();int w=Math.min(480,width-40),x=(width-w)/2;scrollArea(fields.size(),panelTop()+38,panelBottom()-(conflict?136:100),66,x+w+4);for(int n=firstRow;n<Math.min(fields.size(),firstRow+visibleRows);n++){CommunityScreen.Field f=fields.get(n);int y=panelTop()+38+(n-firstRow)*66;if(f.options()!=null){if(!values.has(f.key()))values.addProperty(f.key(),CommunityScreen.optionValue(f.options().get(0)));addRenderableWidget(Button.builder(Component.literal(f.options().asList().stream().filter(o->CommunityScreen.optionValue(o).equals(Json.str(values,f.key()))).map(CommunityScreen::optionLabel).findFirst().orElse("")),b->{int i=0;for(;i<f.options().size();i++)if(CommunityScreen.optionValue(f.options().get(i)).equals(Json.str(values,f.key())))break;values.addProperty(f.key(),CommunityScreen.optionValue(f.options().get((i+1)%f.options().size())));b.setMessage(Component.literal(CommunityScreen.optionLabel(f.options().get((i+1)%f.options().size()))));changed();rebuildWidgets();}).bounds(x,y+15,w,20).build());}else if(Set.of("startsAt","endsAt","dueAt").contains(f.key())){addRenderableWidget(Button.builder(Component.literal(Json.opt(values,f.key(),"").isBlank()?"Выбрать дату и время…":Json.str(values,f.key())),b->minecraft.setScreen(new DateTimeScreen(this,Json.opt(values,f.key(),""),v->{values.addProperty(f.key(),v);changed();}))).bounds(x,y+15,w,20).build());}else if(Set.of("description","text","options","terms","about","reason").contains(f.key())){var edit=addRenderableWidget(new MultiLineEditBox(font,x,y+15,w,40,Component.literal(f.label()),Component.literal(f.label())));edit.setCharacterLimit(f.limit());edit.setValue(Json.opt(values,f.key(),""));edit.setValueListener(v->{values.addProperty(f.key(),v);changed();});}else{var edit=addRenderableWidget(new EditBox(font,x,y+15,w,20,Component.literal(f.label())));edit.setMaxLength(f.limit());edit.setValue(Json.opt(values,f.key(),""));edit.setResponder(v->{values.addProperty(f.key(),v);changed();});}}
            if((fields.stream().anyMatch(f->f.key().equals("title"))&&!Json.opt(values,"kind","").equals("task"))||title.getString().equals("Место"))addRenderableWidget(Button.builder(Component.literal(values.has("location")&&!values.get("location").isJsonNull()?"Место: "+dev.abros.anthub.core.Json.opt(values.getAsJsonObject("location"),"name","указано")+" · Изменить…":"Место не указано · Добавить…"),b->minecraft.setScreen(new LocationEditor(this,values.get("location"),parent.section.equals("groups")||!Json.opt(values,"group","").isEmpty()||parent.data.has("detail")&&parent.data.getAsJsonObject("detail").has("group"),location->{values.add("location",location);changed();}))).bounds(x,panelBottom()-54,w,20).build());
            if(conflict)addRenderableWidget(Button.builder(Component.literal("Обновить запись, сохранив текст"),b->{if(busy)return;var q=new JsonObject();q.addProperty("action","community");q.addProperty("op",values.has("itemId")?"plusItemRead":"detail");if(values.has("itemId"))q.add("itemId",values.get("itemId"));q.addProperty("section",parent.section);q.addProperty("id",parent.itemId);q=session.begin(q,false,System.currentTimeMillis());request=Json.str(q,"request");busy=true;refreshing=true;ServerMenuClient.request(q);}).bounds(x,panelBottom()-88,w,20).build());
            for(var widget:renderables)if(widget instanceof AbstractWidget input)input.active=!busy&&!uncertain;
            var save=addRenderableWidget(Button.builder(Component.literal(busy?"Отправка…":retryable?"Повторить":title.getString().startsWith("Редактировать")?"Сохранить":"Отправить"),b->send()).bounds(x,panelBottom()-28,w/2-3,20).build());save.active=!busy&&!conflict;addRenderableWidget(Button.builder(Component.literal("Назад"),b->onClose()).bounds(x+w/2+3,panelBottom()-28,w/2-3,20).build());}
        private void send(){if(busy)return;fieldErrors.clear();String checking="";var body=values.deepCopy();try{if(recovered!=null){body=session.begin(recovered,true,System.currentTimeMillis());recovered=null;lastValues=values.deepCopy();dispatch(body);return;}for(var f:shownFields()){checking=f.key();String value=Json.opt(values,f.key(),"").strip();if(value.isBlank()&&!Set.of("group","category","invitees","assignee","dueAt","about","interests").contains(f.key()))throw new IllegalArgumentException("Заполните: "+f.label());if(Set.of("days","capacity","quantity","occurrences").contains(f.key())){int n=Integer.parseInt(value);int min=f.key().equals("capacity")?0:f.key().equals("occurrences")?2:1;int max=switch(f.key()){case "days"->90;case "capacity"->300;case "occurrences"->26;default->1000000;};if(n<min||n>max)throw new IllegalArgumentException("От "+min+" до "+max);body.addProperty(f.key(),n);}if(Set.of("startsAt","endsAt","dueAt").contains(f.key())&&!value.isBlank())body.addProperty(f.key(),LocalDateTime.parse(value,DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm").withResolverStyle(java.time.format.ResolverStyle.STRICT)).atZone(ZoneId.systemDefault()).toInstant().toString());if(Set.of("startsAt","endsAt").contains(f.key())&&Instant.parse(body.get(f.key()).getAsString()).isBefore(Instant.now()))throw new IllegalArgumentException("Выберите время в будущем");if(f.key().equals("options")){var options=new JsonArray();for(String s:value.split("\\|"))options.add(s.strip());body.add("options",options);}if(Set.of("multiple","changeVote","liveResults").contains(f.key()))body.addProperty(f.key(),value.equals("Да"));}if(retryable&&lastValues!=null&&lastValues.equals(values)){body=session.retry(System.currentTimeMillis());}else{lastValues=values.deepCopy();body=session.begin(body,true,System.currentTimeMillis());}dispatch(body);}catch(Exception ex){fieldErrors.put(checking,ex instanceof NumberFormatException?"Введите целое число":ex.getMessage());int index=0;for(var f:shownFields()){if(f.key().equals(checking))break;index++;}restoreScroll(index);error="Проверьте выделенное поле";rebuildWidgets();}}
        private String fieldValue(CommunityScreen.Field field,JsonObject source){String key=field.key();JsonElement value=source.get(key);if(source.has("trade")&&source.get("trade").isJsonObject()){var offer=source.getAsJsonObject("trade");if(key.equals("trade"))value=offer.get("type");else if(Set.of("item","quantity","terms").contains(key))value=offer.get(key);}if(value==null||value.isJsonNull())return "Не указано";String text;if(value.isJsonPrimitive()){var p=value.getAsJsonPrimitive();if(Set.of("startsAt","endsAt","dueAt").contains(key)&&p.isNumber()){long time=p.getAsLong();text=time==0?"Не указано":DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm").format(Instant.ofEpochMilli(time).atZone(ZoneId.systemDefault()));}else text=p.isBoolean()?(p.getAsBoolean()?"Да":"Нет"):p.getAsString();}else if(value.isJsonArray()){text=String.join(" | ",value.getAsJsonArray().asList().stream().map(JsonElement::getAsString).toList());}else text="Изменено";if(field.options()!=null)for(var option:field.options())if(CommunityScreen.optionValue(option).equals(text))return CommunityScreen.optionLabel(option);return text.isBlank()?"Не указано":text;}
        private void dispatch(JsonObject body){request=Json.str(body,"request");persist();busy=true;uncertain=true;sentAt=System.currentTimeMillis();error="";var pending=session.command();Client.IO.submit(()->{try{drafts.pending(server,account,draftKey,pending);net.minecraft.client.Minecraft.getInstance().execute(()->{submit.accept(body);});}catch(Exception ex){net.minecraft.client.Minecraft.getInstance().execute(()->{session.cancel();busy=false;uncertain=false;error="Не удалось сохранить состояние отправки. Запрос не отправлен.";rebuildWidgets();});}});rebuildWidgets();}
        public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;uncertain=j.has("error")&&!Set.of("CONFLICT","INVALID","FORBIDDEN","EXPIRED","NOT_FOUND").contains(Json.opt(j,"code",""));if(!uncertain)Client.IO.submit(()->{try{drafts.pending(server,account,draftKey,null);}catch(Exception ignored){}});if(j.has("error")){error=Json.opt(j,"text","Ошибка");conflict=Json.opt(j,"code","").equals("CONFLICT");refreshing=false;retryable=!Set.of("CONFLICT","INVALID","FORBIDDEN","EXPIRED").contains(Json.opt(j,"code",""));rebuildWidgets();return;}if(refreshing){refreshing=false;conflict=false;retryable=false;var latest=j.has("item")?j.getAsJsonObject("item"):j.getAsJsonObject("detail");values.add(j.has("item")?"itemRevision":"revision",latest.get("revision"));var differences=new ArrayList<String>();for(var field:fields){String key=field.key();String current=fieldValue(field,latest),before=fieldValue(field,original);if(!current.equals(before))differences.add(field.label()+"\nСейчас на сервере: "+current+"\nВаш вариант: "+fieldValue(field,values));}original=latest.deepCopy();error="Сохранён ваш вариант. Проверьте изменения перед отправкой.";rebuildWidgets();if(!differences.isEmpty())minecraft.setScreen(new TextScreen(this,Component.literal("Запись изменена другим игроком"),String.join("\n\n",differences)));return;}Client.IO.submit(()->{try{drafts.remove(server,account,draftKey);}catch(Exception ignored){}});saveAt=0;minecraft.setScreen(parent.surface());parent.busy=false;parent.invalidate();}
        @Override public boolean mouseScrolled(double x,double y,double dx,double dy){for(var child:children())if(child instanceof MultiLineEditBox edit&&edit.isMouseOver(x,y)&&edit.mouseScrolled(x,y,dx,dy))return true;return super.mouseScrolled(x,y,dx,dy);}
        @Override public void render(GuiGraphics g,int x,int y,float d){var fields=shownFields();super.render(g,x,y,d);g.drawCenteredString(font,title,width/2,panelTop()+14,0xE2BE75);int left=(width-Math.min(480,width-40))/2;for(int n=firstRow;n<Math.min(fields.size(),firstRow+visibleRows);n++)g.drawString(font,fields.get(n).label(),left,panelTop()+38+(n-firstRow)*66,0xEEEEEE);for(int n=firstRow;n<Math.min(fields.size(),firstRow+visibleRows);n++){String message=fieldErrors.get(fields.get(n).key());if(message!=null)g.drawString(font,font.plainSubstrByWidth(message,Math.min(480,width-40)),left,panelTop()+94+(n-firstRow)*66,0xFF7777);}Ui.status(g,font,error,left,panelBottom()-(conflict?116:80),Math.min(480,width-40),panelBottom()-(conflict?92:56));}
        @Override public void onClose(){persist();session.cancel();minecraft.setScreen(parent.surface());}
        @Override public void tick(){if(saveAt>0&&System.currentTimeMillis()>=saveAt)persist();if(!ServerMenuClient.available()){persist();minecraft.setScreen(null);}else if(session.timeout(System.currentTimeMillis())){if(refreshing){refreshing=false;busy=false;conflict=true;error="Обновление не удалось. Попробуйте ещё раз.";rebuildWidgets();return;}busy=false;uncertain=true;retryable=true;error="Ответ не получен. Повтор безопасен: действие не продублируется.";rebuildWidgets();}}
        @Override public boolean isPauseScreen(){return false;}
    }
