package dev.abros.anthub.client;
import java.util.*;import java.util.function.Consumer;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.*;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.world.item.Item;
final class ItemPickerScreen extends ScrollScreen {
 private final Screen parent;private final Consumer<String> selected;private String query="";private final List<Item> rows=new ArrayList<>();private long changed;
 ItemPickerScreen(Screen parent,Consumer<String> selected){super(Component.literal("Выберите предмет"));this.parent=parent;this.selected=selected;}
 private int w(){return Math.min(420,width-40);}private int x(){return(width-w())/2;}private int top(){return DialogPanel.top(height,330);}private int bottom(){return height-top();}
 @Override protected void init(){var search=addRenderableWidget(new UiEditBox(font,x(),top()+32,w(),20,Component.literal("Поиск предмета")));search.setValue(query);search.setHint(Component.literal("Название предмета"));search.setResponder(v->{query=v;changed=System.currentTimeMillis()+200;});rows.clear();String match=query.toLowerCase(Locale.ROOT);for(var item:BuiltInRegistries.ITEM)if(item!=net.minecraft.world.item.Items.AIR&&(item.getDescription().getString().toLowerCase(Locale.ROOT).contains(match)||BuiltInRegistries.ITEM.getKey(item).toString().contains(match)))rows.add(item);rows.sort(Comparator.comparing(i->i.getDescription().getString()));scrollArea(rows.size(),top()+62,bottom()-36,24,x()+w()+4);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++){var item=rows.get(i);addRenderableWidget(Button.builder(item.getDescription(),b->{if(changed!=0)return;minecraft.setScreen(parent);selected.accept(BuiltInRegistries.ITEM.getKey(item).toString());}).bounds(x()+24,top()+62+(i-firstRow)*24,w()-24,20).tooltip(Tooltip.create(Component.literal(BuiltInRegistries.ITEM.getKey(item).toString()))).build());}addRenderableWidget(Button.builder(Component.literal("Назад"),b->onClose()).bounds(x(),bottom()-28,w(),20).build());}
 @Override public void tick(){if(changed>0&&System.currentTimeMillis()>=changed){changed=0;resetScroll();rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);DialogPanel.draw(g,width,w(),top(),bottom());}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++)g.renderItem(rows.get(i).getDefaultInstance(),x()+2,top()+64+(i-firstRow)*24);if(rows.isEmpty())Ui.text(g,font,"Предмет не найден",x(),top()+66,UiPalette.color(0xAEBBC8));}
 @Override public void onClose(){minecraft.setScreen(parent);}@Override public boolean isPauseScreen(){return false;}
}
