package dev.abros.anthub.client;
import com.google.gson.*;
import dev.abros.anthub.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import java.util.*;
/** Public places remain server-owned; map visibility is a separate local preference. */
final class PlacesScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final RequestSession session=new RequestSession();private JsonArray places=new JsonArray();private boolean loaded,busy,retry;private String cursor="",next="",notice="";
 PlacesScreen(Screen parent){super(Component.literal("Общедоступные места"));this.parent=parent;}
 private int w(){return Math.min(470,width-40);}private int x(){return (width-w())/2;}private int top(){return DialogPanel.top(height,360);}private int bottom(){return height-top();}
 private void request(String op,JsonObject body){if(busy)return;body.addProperty("action","community");body.addProperty("section","home");body.addProperty("op",op);busy=true;retry=false;ServerMenuClient.request(session.begin(body,!op.equals("toolsPlaces"),System.currentTimeMillis()));rebuildWidgets();}
 private void load(){var j=new JsonObject();j.addProperty("cursor",cursor);request("toolsPlaces",j);}
 private void edit(JsonObject row){minecraft.setScreen(new LocationEditor(this,row==null?null:row.get("location"),false,value->{if(value==null||value.isJsonNull()){notice="Для удаления используйте действие в карточке места";return;}var j=row==null?new JsonObject():row.deepCopy();j.add("location",value);j.addProperty("title",Json.str(value.getAsJsonObject(),"name"));request("toolsPlaceSave",j);}));}
 private Button button(String label,int xx,int y,int width,Runnable action){var b=addRenderableWidget(Button.builder(Component.literal(font.plainSubstrByWidth(label,width-12)),v->action.run()).bounds(xx,y,width,20).build());b.active=!busy&&!retry;return b;}
 @Override protected void init(){button("+ Добавить место",x(),top()+32,(w()-8)/2,()->edit(null));button("Слой на карте: "+(MapLayerClient.placesShown()?"да":"нет"),x()+(w()+8)/2,top()+32,(w()-8)/2,()->{MapLayerClient.togglePlaces();rebuildWidgets();});scrollArea(places.size(),top()+64,bottom()-80,72,x()+w()+4);for(int n=firstRow;n<Math.min(places.size(),firstRow+visibleRows);n++){var row=places.get(n).getAsJsonObject();int y=top()+64+(n-firstRow)*72;String id=Json.str(row,"id");button("Координаты",x()+6,y+26,100,()->minecraft.keyboardHandler.setClipboard(CommunityLocation.read(row.getAsJsonObject("location")).coordinates()));button(MapLayerClient.hidden(id)?"Показать на карте":"Скрыть на карте",x()+112,y+26,142,()->{MapLayerClient.hide(id);rebuildWidgets();});if(row.get("manage").getAsBoolean())button("Изменить…",x()+w()-102,y+26,96,()->minecraft.setScreen(new ChoicePopup(this,"Место",List.of("Название и координаты","Статус места","Удалить с сервера…"),i->{if(i==0)edit(row);else if(i==1)minecraft.setScreen(new ChoicePopup(this,"Статус",List.of("Доступно","Временно недоступно","Закрыто"),s->{var j=row.deepCopy();j.addProperty("status",List.of("open","unavailable","closed").get(s));request("toolsPlaceSave",j);}));else minecraft.setScreen(new ConfirmScreen(yes->{minecraft.setScreen(this);if(yes)request("toolsPlaceDelete",row.deepCopy());},Component.literal("Удалить общедоступное место?"),Component.literal(Json.str(row,"title"))));})));}
 if(retry)button("Повторить",x(),bottom()-54,w(),()->{busy=true;retry=false;ServerMenuClient.request(session.retry(System.currentTimeMillis()));rebuildWidgets();}).active=true;else if(!next.isEmpty())button("Следующая страница",x(),bottom()-54,w(),()->{cursor=next;resetScroll();load();});else if(!cursor.isEmpty())button("К началу списка",x(),bottom()-54,w(),()->{cursor="";resetScroll();load();});addRenderableWidget(Button.builder(Component.literal("Назад"),b->onClose()).bounds(x(),bottom()-28,w(),20).build());if(!loaded){loaded=true;load();}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("error")){notice=Json.opt(j,"text","Не удалось загрузить места");retry=true;}else if(j.has("places")){places=j.getAsJsonArray("places");next=Json.opt(j,"nextCursor","");notice=places.isEmpty()?"Мест пока нет":"";}else{MapLayerClient.refreshPlaces();load();return;}rebuildWidgets();}
 @Override public void tick(){if(session.timeout(System.currentTimeMillis())){busy=false;retry=true;notice="Нет ответа. Повтор безопасен.";rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);DialogPanel.draw(g,width,w(),top(),bottom());for(int n=firstRow;n<Math.min(places.size(),firstRow+visibleRows);n++){int y=top()+64+(n-firstRow)*72;g.fill(x(),y,x()+w(),y+64,AccessibilityScreen.background(UiPalette.color(0xB02D3B46)));}}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());for(int n=firstRow;n<Math.min(places.size(),firstRow+visibleRows);n++){var row=places.get(n).getAsJsonObject();int y=top()+64+(n-firstRow)*72;String status=switch(Json.opt(row,"status","open")){case "closed"->"Закрыто";case "unavailable"->"Недоступно";default->"Доступно";};g.drawString(font,font.plainSubstrByWidth(Json.str(row,"title")+" · "+status,w()-16),x()+6,y+6,UiPalette.color(0xD7E2EC));g.drawString(font,font.plainSubstrByWidth("Автор: "+Json.str(row,"author"),w()-16),x()+6,y+52,UiPalette.color(0xBAC7D2));}Ui.status(g,font,notice,x(),bottom()-78,w(),bottom()-56);}
 @Override public void onClose(){session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
