package dev.abros.anthub.client;
import com.google.gson.*;
import dev.abros.anthub.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;
/** One task surface for personal work and group projects. */
final class TaskScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final String group;private String id,notice="",taskTab="Обзор";private JsonObject data=new JsonObject();private final RequestSession session=new RequestSession();private boolean loaded,busy,retry,dirty;private String requestId="",operation="";private String query="",statusFilter="",listedQuery="",listedStatus="";private long searchAt;private String cursor="";private JsonArray tasks=new JsonArray();private boolean listLoaded,canCreate;private final MenuSidebar nav=new MenuSidebar(this);private final RowViewport taskList=new RowViewport();
 private final Map<Integer,Runnable> stageMenus=new HashMap<>();private final Map<Integer,List<String>> paragraphs=new HashMap<>();private final Map<Integer,Boolean> stageChecks=new HashMap<>();private final Map<Integer,Double> resourceProgress=new HashMap<>();private final Map<Integer,String> resourceIcons=new HashMap<>();private final List<String> lines=new ArrayList<>();private final List<Runnable> actions=new ArrayList<>();
 TaskScreen(Screen parent,String group,String id){super(Component.literal(group.isEmpty()?"Мои задачи":"Задачи объединения"));this.parent=parent;this.group=group;this.id=id;}
 boolean matches(JsonObject j){return requestId.equals(Json.opt(j,"request",""));}
 boolean leavePage(){if(busy&&!Set.of("workList","workGet").contains(operation))return false;if(busy){session.cancel();busy=false;dirty=true;}return true;}
 boolean personal(){return group.isEmpty();}
 static boolean available(){return ServerMenuClient.supports("task-tools");}
 private boolean split(){return width-nav.left()>=420;}
 private int listWidth(){return split()?Math.min(230,Math.max(150,(width-nav.left()-32)/3)):width-nav.left()-20;}
 private int x(){return split()?nav.left()+listWidth()+12:nav.left();}
 private int w(){return width-x()-20;}
 private int top(){return 38;}
 private int panelEnd(){if(!data.has("task"))return Math.min(height-64,top()+72);return Math.min(height-64,top()+Math.max(166,Math.min(360,98+lines.size()*24)));}
 private int bottom(){return height-34;}
 private int listBottom(){return height-64;}
 private void list(){var j=new JsonObject();j.addProperty("group",group);j.addProperty("query",query);j.addProperty("status",statusFilter);if(!cursor.isEmpty())j.addProperty("cursor",cursor);send("workList",j);}
 private void select(JsonObject task){if(busy){if(!Set.of("workList","workGet").contains(operation))return;ServerMenuClient.cancelReads(this);session.cancel();busy=false;}String next=Json.str(task,"id");if(next.equals(id)&&data.has("task"))return;id=next;taskTab="Обзор";data.remove("task");resetScroll();load();}
 String subscription(){return group.isEmpty()?"home|":"groups|"+group;}
 void invalidate(String section,String target){if(section.equals(group.isEmpty()?"home":"groups")&&(group.isEmpty()||target.isEmpty()||target.equals(group)))dirty=true;}
 private JsonObject body(){var j=new JsonObject();if(id.isEmpty()&&!cursor.isEmpty())j.addProperty("cursor",cursor);j.addProperty("group",group);if(!id.isEmpty()){j.addProperty("task",id);if(data.has("task"))j.add("revision",data.getAsJsonObject("task").get("revision"));}return j;}
 private void send(String op,JsonObject j){if(busy)return;j.addProperty("action","community");j.addProperty("section","home");j.addProperty("op",op);busy=true;retry=false;notice=Set.of("workList","workGet").contains(op)?"Загрузка…":"Сохраняем изменения…";operation=op;var packet=session.begin(j,!Set.of("workList","workGet").contains(op),System.currentTimeMillis());requestId=Json.str(packet,"request");ServerMenuClient.request(packet);if(!Set.of("workList","workGet").contains(op)||!listLoaded||!id.isEmpty()&&!data.has("task"))rebuildWidgets();}
 private void load(){send(id.isEmpty()?"workList":"workGet",body());}
 private void row(String label,Runnable action){lines.add(label);actions.add(action);}
 private void paragraph(String text){var wrapped=font.getSplitter().splitLines(text,w()-24,net.minecraft.network.chat.Style.EMPTY);for(int i=0;i<wrapped.size();i+=2){var pair=new ArrayList<String>();pair.add(wrapped.get(i).getString());if(i+1<wrapped.size())pair.add(wrapped.get(i+1).getString());paragraphs.put(lines.size(),pair);row("",null);}}
 private void stageMenu(JsonObject stage,int index){minecraft.setScreen(new ChoicePopup(this,"Этап",List.of("Переименовать…","Удалить этап…"),choice->{if(choice==0){var preset=new JsonObject();preset.add("title",stage.get("title"));editor("Название этапа",List.of(new CommunityScreen.Field("title","Название",100)),preset,v->{var b=body();b.addProperty("index",index);b.add("title",v.get("title"));send("workSubtask",b);});}else minecraft.setScreen(new net.minecraft.client.gui.screens.ConfirmScreen(yes->{minecraft.setScreen(this);if(yes){var b=body();b.addProperty("index",index);b.addProperty("remove",true);send("workSubtask",b);}},Component.literal("Удалить этап?"),Component.literal(Json.str(stage,"title"))));}));}
 private void editor(String title,List<CommunityScreen.Field> fields,JsonObject preset,java.util.function.Consumer<JsonObject> callback){minecraft.setScreen(new TaskEditScreen(this,title,fields,preset,callback));}
 private void edit(JsonObject t){if(busy){notice="Дождитесь завершения текущего запроса";return;}var preset=new JsonObject();if(t!=null)for(String k:List.of("title","description"))preset.add(k,t.has(k)?t.get(k):new JsonPrimitive(""));editor(t==null?"Новая задача":"Изменить задачу",List.of(new CommunityScreen.Field("title","Название",100),new CommunityScreen.Field("description","Описание",1000)),preset,v->{var b=body();if(t==null){b.remove("task");b.remove("revision");}b.add("title",v.get("title"));b.add("description",v.has("description")?v.get("description"):new JsonPrimitive(""));send("workSave",b);});}
 private void textAction(String title,String key,int limit,String op){editor(title,List.of(new CommunityScreen.Field(key,title,limit)),new JsonObject(),v->{var b=body();b.add(key,v.get(key));send(op,b);});}
 private boolean planning(){return ServerMenuClient.supports("community-extensions");}
 private void planningRows(JsonObject t,boolean manage){
  var deps=t.has("dependencyDetails")?t.getAsJsonArray("dependencyDetails"):new JsonArray();
  row(deps.isEmpty()?"Нет блокирующих задач":"Сначала выполнить",null);
  var codes=new ArrayList<String>();for(var e:deps){var d=e.getAsJsonObject();String code=Json.opt(d,"code","");codes.add(code);paragraph((d.get("done").getAsBoolean()?"Готово: ":"Ожидается: ")+code+" · "+Json.str(d,"title"));}
  if(manage)row("Изменить зависимости…",()->{var preset=new JsonObject();preset.addProperty("codes",String.join(", ",codes));editor("Коды блокирующих задач",List.of(new CommunityScreen.Field("codes","Коды через запятую; пусто — убрать",200)),preset,v->{var b=body();b.add("codes",v.get("codes"));send("workDependencies",b);});});
  int days=t.has("repeatDays")?t.get("repeatDays").getAsInt():0;var intervals=List.of(0,1,7,30);var labels=List.of("Не повторять","Каждый день","Каждые 7 дней","Каждые 30 дней");
  row("Повтор: "+labels.get(Math.max(0,intervals.indexOf(days)))+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,"Повтор задачи",labels,n->{var b=body();b.addProperty("days",intervals.get(n));send("workRepeat",b);}).current(intervals.indexOf(days))):null);
  if(days>0)paragraph("Следующая отдельная задача: "+CommunityScreen.local(t.get("nextRepeatAt").getAsLong()));
 }
 private static String historyLabel(String op){return switch(op){case "workSave"->"Изменены название и описание";case "workStatus"->"Изменён статус";case "workAssign"->"Изменён ответственный";case "workDue"->"Изменён срок";case "workSubtask"->"Изменён этап";case "workResources"->"Изменены ресурсы";case "workDependencies"->"Изменены зависимости";case "workReserve"->"Изменён резерв";case "workRepeat"->"Изменён повтор";case "workComment"->"Добавлен комментарий";default->"Изменена задача";};}
 private void resources(){var t=data.getAsJsonObject("task");minecraft.setScreen(new TaskResourcesScreen(this,t.has("resources")?t.getAsJsonArray("resources"):new JsonArray(),rows->{var request=body();request.add("resources",rows);send("workResources",request);}));}
 @Override protected void init(){lines.clear();actions.clear();stageChecks.clear();stageMenus.clear();paragraphs.clear();resourceIcons.clear();resourceProgress.clear();
  if(data.has("task")){var t=data.getAsJsonObject("task");boolean manage=t.get("manage").getAsBoolean();if(taskTab.equals("Обзор")){row("Скопировать код: "+Json.str(t,"code"),()->{minecraft.keyboardHandler.setClipboard(Json.str(t,"code"));notice="Код скопирован";});paragraph(Json.opt(t,"description",""));
   if(manage||Json.opt(t,"assignee","").equals(CommunityScreen.me()))row("Статус: "+status(t)+" ▾",()->minecraft.setScreen(new ChoicePopup(this,"Статус задачи",List.of("Открыта","В работе","Готово"),n->{var b=body();b.addProperty("status",List.of("open","working","done").get(n));send("workStatus",b);}).current(List.of("open","working","done").indexOf(Json.opt(t,"status","open")))));
   row("Ответственный: "+Json.opt(t,"assigneeName","Не назначен")+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,"Ответственный",List.of("Выбрать участника","Снять назначение"),n->{if(n==1){var b=body();b.addProperty("assignee","");send("workAssign",b);}else if(group.isEmpty()){var b=body();b.addProperty("assignee",CommunityScreen.me());send("workAssign",b);}else minecraft.setScreen(new TaskMemberPicker(this,group,p->{var b=body();b.add("assignee",p.get("uuid"));send("workAssign",b);}));})):null);long due=t.has("dueAt")?t.get("dueAt").getAsLong():0;row((due==0?"Срок не задан":"Срок: "+CommunityScreen.local(due))+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,"Срок задачи",List.of("Выбрать дату и время","Убрать срок"),n->{if(n==1){var b=body();b.addProperty("dueAt",0);send("workDue",b);}else minecraft.setScreen(new DateTimeScreen(this,"",v->{var b=body();b.addProperty("dueAt",java.time.LocalDateTime.parse(v,java.time.format.DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm")).atZone(AccessibilityScreen.zone()).toInstant().toEpochMilli());send("workDue",b);}));})):null);}if(planning()&&taskTab.equals("Обзор")){planningRows(t,manage);}if(taskTab.equals("Этапы")){var stages=t.has("subtasks")?t.getAsJsonArray("subtasks"):new JsonArray();long done=java.util.stream.StreamSupport.stream(stages.spliterator(),false).filter(e->e.getAsJsonObject().get("done").getAsBoolean()).count();row(stages.isEmpty()?"Разбейте задачу на небольшие шаги":"Выполнено: "+done+" из "+stages.size(),null);int n=0;for(var e:stages){int index=n++;var stage=e.getAsJsonObject();int line=lines.size();stageChecks.put(line,stage.get("done").getAsBoolean());row(Json.str(stage,"title"),manage||CommunityScreen.me().equals(Json.opt(stage,"assignee",""))?()->{var b=body();b.addProperty("index",index);send("workSubtask",b);}:null);if(manage)stageMenus.put(line,()->stageMenu(stage,index));}if(manage)row("Добавить этап…",()->textAction("Название этапа","title",100,"workSubtask"));
   }if(taskTab.equals("Ресурсы")){row("Ресурсы",null);var counts=new HashMap<String,Long>();long confirmed=0;if(t.has("stocks"))for(var e:t.getAsJsonArray("stocks")){var stock=e.getAsJsonObject();confirmed=Math.max(confirmed,stock.has("at")?stock.get("at").getAsLong():0);if(stock.has("items"))for(var item:stock.getAsJsonObject("items").entrySet())counts.merge(item.getKey(),item.getValue().getAsLong(),Long::sum);}
   if(t.has("resources"))for(var e:t.getAsJsonArray("resources")){var res=e.getAsJsonObject();resourceProgress.put(lines.size(),Math.min(1,counts.getOrDefault(Json.str(res,"item"),0L)/(double)Math.max(1,res.get("amount").getAsInt())));resourceIcons.put(lines.size(),Json.str(res,"item"));row(TaskResourcesScreen.name(Json.str(res,"item"))+": "+counts.getOrDefault(Json.str(res,"item"),0L)+" / "+res.get("amount").getAsInt(),null);}row(confirmed==0?"Склад ещё не проверен сервером":"Проверено: "+CommunityScreen.local(confirmed),null);if(manage){row("Изменить список ресурсов",this::resources);row("Как подключить сундук",()->minecraft.setScreen(new TaskStockSignScreen(this,data.getAsJsonObject("task").deepCopy())));}
   }if(planning()&&taskTab.equals("Ресурсы")){
   var pool=t.has("confirmedPool")?t.getAsJsonObject("confirmedPool"):new JsonObject();var used=t.has("reservedElsewhere")?t.getAsJsonObject("reservedElsewhere"):new JsonObject();var mine=t.has("reservations")?t.getAsJsonObject("reservations"):new JsonObject();
   row("Резерв общего запаса",null);if(t.has("resources"))for(var e:t.getAsJsonArray("resources")){var res=e.getAsJsonObject();String item=Json.str(res,"item");long total=pool.has(item)?pool.get(item).getAsLong():0,others=used.has(item)?used.get(item).getAsLong():0,own=mine.has(item)?mine.get(item).getAsLong():0;paragraph(TaskResourcesScreen.name(item)+": свободно "+Math.max(0,total-others-own)+", этой задаче "+own+", другим "+others);}
   paragraph("Резерв учитывается AntHub по последней проверке сервера. Предметы в сундуках остаются доступны игрокам.");
   if(manage)row(mine.size()>0?"Снять резерв":"Зарезервировать требуемые ресурсы",()->{var b=body();b.addProperty("release",mine.size()>0);send("workReserve",b);});
   }if(planning()&&taskTab.equals("История")){row("Последние изменения",null);var events=t.has("history")?t.getAsJsonArray("history"):new JsonArray();if(events.isEmpty())row("Изменений ещё нет",null);for(int i=events.size()-1;i>=0;i--){var event=events.get(i).getAsJsonObject();paragraph(CommunityScreen.local(event.get("at").getAsLong())+" · "+Json.str(event,"author")+"\n"+historyLabel(Json.str(event,"operation")));}}
   if(taskTab.equals("Комментарии")){row("Комментарии",null);if(t.has("comments"))for(var e:t.getAsJsonArray("comments")){var c=e.getAsJsonObject();paragraph(Json.str(c,"author")+": "+Json.str(c,"text"));}row("+ Комментарий",()->textAction("Комментарий","text",500,"workComment"));}
  }
  nav.build(group.isEmpty()?"tasks":"groups",this::addRenderableWidget);
  int lw=listWidth();if(split()||id.isEmpty()){var search=addRenderableWidget(new UiEditBox(font,nav.left(),38,lw-54,20,Component.literal("Поиск задач")));search.setHint(Component.literal("Поиск задач"));search.setMaxLength(100);search.setValue(query);search.setResponder(v->{query=v;searchAt=System.currentTimeMillis()+500;});addRenderableWidget(Button.builder(Component.literal("Найти"),b->resetList()).bounds(nav.left()+lw-50,38,50,20).build());
  addRenderableWidget(Button.builder(Component.literal((statusFilter.isEmpty()?"Все":statusFilter.equals("working")?"В работе":statusFilter.equals("done")?"Готово":"Открыты")+" ▾"),b->minecraft.setScreen(new ChoicePopup(this,"Показать задачи",List.of("Все","Открытые","В работе","Готовые"),n->{statusFilter=List.of("","open","working","done").get(n);resetList();},b).current(List.of("","open","working","done").indexOf(statusFilter)))).bounds(nav.left(),64,lw-28,20).build());addRenderableWidget(Button.builder(Component.literal("×"),b->{query="";statusFilter="";resetList();rebuildWidgets();}).bounds(nav.left()+lw-24,64,24,20).tooltip(Tooltip.create(Component.literal("Сбросить поиск и фильтр задач"))).build()).active=!query.isBlank()||!statusFilter.isEmpty();var create=addRenderableWidget(Button.builder(Component.literal("Новая задача"),b->edit(null)).bounds(nav.left(),88,Math.min(lw,134),20).build());create.active=!busy&&!retry&&(group.isEmpty()||canCreate);if(!create.active)create.setTooltip(Tooltip.create(Component.literal(busy?"Дождитесь завершения текущего запроса":retry?"Сначала повторите запрос к серверу":"Создавать задачи могут руководители объединения")));
  int stride=AccessibilityScreen.compact()?60:76;taskList.layout(tasks.size(),114,listBottom(),stride,nav.left()+lw+2);
  for(int n=taskList.first();n<Math.min(tasks.size(),taskList.first()+taskList.visible());n++){var task=tasks.get(n).getAsJsonObject();var card=task.deepCopy();card.addProperty("section","task");card.addProperty("attention",(Json.opt(task,"code","").isBlank()?"":Json.opt(task,"code","")+" · ")+status(task));card.addProperty("preview",Json.opt(task,"preview",Json.opt(task,"description",Json.opt(task,"assigneeName","Не назначен"))));long due=task.has("dueAt")?task.get("dueAt").getAsLong():0;card.addProperty("footer",(task.has("stagesTotal")&&task.get("stagesTotal").getAsInt()>0?"Этапы: "+task.get("stagesDone").getAsInt()+" / "+task.get("stagesTotal").getAsInt()+" · ":"")+(due>0?"До "+java.time.Instant.ofEpochMilli(due).atZone(AccessibilityScreen.zone()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM HH:mm")):"Без срока"));var widget=addRenderableWidget(new CommunityCard(nav.left(),114+(n-taskList.first())*stride,lw,stride-6,card,()->select(task)));widget.selected=Json.str(task,"id").equals(id);widget.active=!busy;}
  }else taskList.layout(0,114,114,24,nav.left());
  if(data.has("task")){var t=data.getAsJsonObject("task");if(t.get("manage").getAsBoolean())addRenderableWidget(Button.builder(Component.literal("Действия ▾"),b->minecraft.setScreen(new ChoicePopup(this,"Действия с задачей",List.of("Редактировать","Удалить…"),n->{if(n==0)edit(t);else minecraft.setScreen(new net.minecraft.client.gui.screens.ConfirmScreen(yes->{minecraft.setScreen(this);if(yes)send("workDelete",body());},Component.literal("Удалить задачу?"),Component.literal("Этапы, комментарии и привязки складов будут удалены.")));},b))).bounds(x()+w()-92,top()+8,84,20).tooltip(Tooltip.create(Component.literal("Редактирование и удаление задачи"))).build()).active=!busy;var tabs=planning()?List.of("Обзор","Этапы","Ресурсы","Комментарии","История"):List.of("Обзор","Этапы","Ресурсы","Комментарии");if(w()<420){addRenderableWidget(Button.builder(Component.literal(taskTab+" ▾"),b->minecraft.setScreen(new ChoicePopup(this,"Раздел задачи",tabs,n->{taskTab=tabs.get(n);resetScroll();rebuildWidgets();},b).current(tabs.indexOf(taskTab)))).bounds(x()+8,top()+50,w()-16,20).build());}else{int bw=(w()-12-4*tabs.size())/tabs.size();for(int i=0;i<tabs.size();i++){String tab=tabs.get(i);addRenderableWidget(new TabButton(x()+8+i*(bw+4),top()+50,bw,tab,tab.equals(taskTab),()->{taskTab=tab;resetScroll();rebuildWidgets();}));}}}
  scrollArea(lines.size(),top()+82,panelEnd()-12,24,x()+w()-7);for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++){int y=top()+82+(n-firstRow)*24;String rowLabel=lines.get(n);var action=actions.get(n);if(stageChecks.containsKey(n)){var check=addRenderableWidget(new UiChoiceRow(x()+8,y,w()-(stageMenus.containsKey(n)?54:24),rowLabel,stageChecks.get(n),-1,UiKit.ACCENT,()->{if(action!=null)action.run();}));check.active=action!=null&&!busy&&!retry;if(stageMenus.containsKey(n)){var menu=stageMenus.get(n);addRenderableWidget(Button.builder(Component.literal("⋯"),b->{menu.run();if(minecraft.screen instanceof ChoicePopup popup)popup.attach(b);}).bounds(x()+w()-34,y,22,20).tooltip(Tooltip.create(Component.literal("Переименовать или удалить этап"))).build()).active=!busy&&!retry;}}else if(action!=null){int bw=Math.min(w()-24,Math.max(80,Math.min(280,font.width(lines.get(n))+38)));var button=addRenderableWidget(Button.builder(Component.literal(lines.get(n)),b->{action.run();if(rowLabel.endsWith(" ▾")&&minecraft.screen instanceof ChoicePopup popup)popup.attach(b);}).bounds(x()+8,y,bw,20).build());if(font.width(lines.get(n))>bw-16)button.setTooltip(Tooltip.create(Component.literal(lines.get(n))));button.active=!busy&&!retry;}}
  if(!cursor.isEmpty()||!cursorNext().isEmpty())addRenderableWidget(Button.builder(Component.literal(cursorNext().isEmpty()?"К началу списка":"Следующая страница"),b->{cursor=cursorNext();taskList.reset();list();}).bounds(nav.left(),height-56,Math.min(lw,150),20).build()).active=!busy;
  if(retry)addRenderableWidget(Button.builder(Component.literal("Повторить"),b->{busy=true;retry=false;var packet=session.retry(System.currentTimeMillis());requestId=Json.str(packet,"request");ServerMenuClient.request(packet);rebuildWidgets();}).bounds(nav.left(),height-28,90,20).build());else addRenderableWidget(Button.builder(Component.literal(!split()&&!id.isEmpty()?"К списку":"Обновить"),b->{if(!split()&&!id.isEmpty()){id="";data.remove("task");resetScroll();rebuildWidgets();}else list();}).bounds(nav.left(),height-28,90,20).build()).active=!busy;
  addRenderableWidget(Button.builder(Component.literal("Назад"),b->onClose()).bounds(width-100,height-28,80,20).build());if(!loaded){loaded=true;list();}
 }
 private String nextCursor="";private String cursorNext(){return nextCursor;}
 
 private static String status(JsonObject t){return switch(Json.opt(t,"status","open")){case "working"->"В работе";case "done"->"Готово";default->"Открыта";};}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;boolean wasBusy=busy;busy=false;boolean changed=false;
  if(j.has("error")){notice=Json.opt(j,"text","Не удалось выполнить действие");retry=!Set.of("INVALID","FORBIDDEN","NOT_FOUND","CONFLICT","EXPIRED").contains(Json.opt(j,"code",""));if(Json.opt(j,"code","").equals("CONFLICT")&&!(minecraft.screen instanceof TaskEditScreen)&&!(minecraft.screen instanceof TaskResourcesScreen)){load();return;}changed=true;}
  else{notice="";if(j.has("deleted")){for(int n=tasks.size()-1;n>=0;n--)if(Json.str(tasks.get(n).getAsJsonObject(),"id").equals(id))tasks.remove(n);id="";data.remove("task");rebuildWidgets();return;}
   if(j.has("tasks")){changed=!listLoaded||!tasks.equals(j.get("tasks"))||!nextCursor.equals(Json.opt(j,"nextCursor",""))||canCreate!=(j.has("canCreate")&&j.get("canCreate").getAsBoolean());tasks=j.getAsJsonArray("tasks").deepCopy();if(id.isEmpty()&&split()&&!tasks.isEmpty()){id=Json.str(tasks.get(0).getAsJsonObject(),"id");changed=true;}nextCursor=Json.opt(j,"nextCursor","");listLoaded=true;canCreate=j.has("canCreate")&&j.get("canCreate").getAsBoolean();if(!id.isEmpty()){if(changed)rebuildWidgets();load();return;}}
   if(j.has("task")){var task=j.getAsJsonObject("task");id=Json.str(task,"id");changed=!data.has("task")||!UiPayload.same(data.getAsJsonObject("task"),task);data.add("task",task.deepCopy());boolean found=false;for(int n=0;n<tasks.size();n++)if(Json.str(tasks.get(n).getAsJsonObject(),"id").equals(id)){tasks.set(n,task.deepCopy());found=true;break;}if(!found)tasks.add(task.deepCopy());}
  }if(changed||retry||wasBusy&&!Set.of("workList","workGet").contains(operation))rebuildWidgets();
 }
 private void resetList(){if(busy)return;if(!query.equals(listedQuery)||!statusFilter.equals(listedStatus)){id="";data.remove("task");taskTab="Обзор";resetScroll();}listedQuery=query;listedStatus=statusFilter;cursor="";searchAt=0;taskList.reset();list();}
 @Override public boolean keyPressed(int key,int scan,int modifiers){if((key==264||key==265)&&getFocused() instanceof CommunityCard focused){int at=-1;for(int n=0;n<tasks.size();n++)if(Json.str(tasks.get(n).getAsJsonObject(),"id").equals(focused.targetId())){at=n;break;}if(at>=0){int next=Math.max(0,Math.min(tasks.size()-1,at+(key==264?1:-1)));taskList.reveal(next);String target=Json.str(tasks.get(next).getAsJsonObject(),"id");rebuildWidgets();for(var c:children())if(c instanceof CommunityCard card&&card.targetId().equals(target)){setFocused(card);break;}return true;}}if((key==257||key==335)&&getFocused() instanceof EditBox){resetList();return true;}if(key==256&&!id.isEmpty()){id="";data.remove("task");rebuildWidgets();return true;}return super.keyPressed(key,scan,modifiers);}
 @Override public void tick(){if(searchAt>0&&!busy&&!retry&&System.currentTimeMillis()>=searchAt)resetList();if(dirty&&!busy&&!retry){dirty=false;list();}if(session.timeout(System.currentTimeMillis())){busy=false;retry=true;notice="Нет ответа. Повтор безопасен.";rebuildWidgets();}}
 @Override public boolean mouseScrolled(double mx,double my,double dx,double dy){if(nav.scroll(mx,dy)){rebuildWidgets();return true;}if((split()?mx<x():my<listBottom())&&taskList.scroll(my,dy)){rebuildWidgets();return true;}return super.mouseScrolled(mx,my,dx,dy);}
 @Override public boolean mouseClicked(double mx,double my,int button){if(taskList.click(mx,my,button)){rebuildWidgets();return true;}return super.mouseClicked(mx,my,button);}
 @Override public boolean mouseDragged(double mx,double my,int button,double dx,double dy){if(taskList.drag(my,button)){rebuildWidgets();return true;}return super.mouseDragged(mx,my,button,dx,dy);}
 @Override public boolean mouseReleased(double mx,double my,int button){taskList.release();return super.mouseReleased(mx,my,button);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);if(!id.isEmpty()){UiTheme.panel(g,x(),top(),w(),panelEnd()-top(),UiPalette.color(0xE81B252E));}}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);UiHeading.page(g,font,title,width);taskList.draw(g);if((split()||id.isEmpty())&&tasks.isEmpty()&&!busy)UiEmptyState.draw(g,font,listLoaded?query.isBlank()&&statusFilter.isEmpty()?"Начните с первой задачи":"Задачи не найдены":"Загрузка…",query.isBlank()&&statusFilter.isEmpty()?"Нажмите «Новая задача» и добавьте первый шаг.":"Измените запрос или сбросьте фильтр кнопкой ×.",nav.left()+8,122,listWidth()-16,listBottom());if(data.has("task")){var task=data.getAsJsonObject("task");Ui.text(g,font,font.plainSubstrByWidth(Json.str(task,"title"),w()-108),x()+12,top()+14,UiKit.text(),false);UiBadge.draw(g,font,Json.opt(task,"code","")+" · "+status(task),x()+12,top()+29,w()-24,Json.opt(task,"status","open").equals("done")?UiPalette.color(0xFF79CBA6):UiPalette.color(0xFFF0A77C));}if(!data.has("task")&&split())UiEmptyState.draw(g,font,id.isEmpty()?"Ваш следующий шаг":"Открываем задачу…",id.isEmpty()?"Выберите карточку слева или создайте новую задачу.":"Получаем актуальные данные с сервера.",x()+12,top()+16,w()-24,top()+70);
  for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++)if(actions.get(n)==null&&!stageChecks.containsKey(n)){int y=top()+82+(n-firstRow)*24;if(paragraphs.containsKey(n)){int line=0;for(String text:paragraphs.get(n))Ui.text(g,font,text,x()+12,y+2+12*line++,UiKit.text(),false);continue;}String item=resourceIcons.get(n);if(item!=null)TaskResourcesScreen.icon(g,item,x()+8,y+2);Ui.text(g,font,font.plainSubstrByWidth(lines.get(n),w()-(item==null?24:44)),x()+(item==null?12:30),y+5,UiPalette.color(0xD7E2EC));if(resourceProgress.containsKey(n)){g.fill(x()+30,y+19,x()+w()-24,y+21,UiPalette.color(0xFF394651));g.fill(x()+30,y+19,x()+30+(int)((w()-54)*resourceProgress.get(n)),y+21,UiPalette.color(0xFF79CBA6));}}Ui.status(g,font,notice,x(),height-56,w(),height-34);}
 @Override public void onClose(){session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
