package dev.abros.anthub.core;
import com.google.gson.*;
import java.util.*;
/** Support tickets share the server PostgreSQL database. */
public final class CommunityReports {
 private final CommunityStore db;
 public CommunityReports(CommunityStore db){this.db=db;}
 public String submit(UUID player,String name,JsonObject in,long now)throws Exception{return db.inTransaction(()->{db.checkReport(player.toString(),now);String message=Json.str(in,"message").strip();if(message.isEmpty()||message.length()>1500)throw new IllegalArgumentException("Текст обращения: 1–1500 символов");var j=new JsonObject();String id=UUID.randomUUID().toString();j.addProperty("id",id);j.addProperty("uuid",player.toString());j.addProperty("player",name);j.addProperty("createdAt",now);j.addProperty("message",message);j.addProperty("status","open");String category=Json.opt(in,"category","technical");if(!Set.of("technical","player","appeal","other").contains(category))throw new IllegalArgumentException("Неизвестная категория обращения");j.addProperty("category",category);j.addProperty("revision",1);for(String k:List.of("coreVersion","packVersion","repository","audit")){String v=Json.opt(in,k,"");if(v.length()>(k.equals("audit")?2000:512))throw new IllegalArgumentException("Поле слишком длинное");j.addProperty(k,v);}db.record("reports",id,j);return id;});}
 public JsonArray list(UUID owner,int page)throws Exception{if(page<0||page>1000)throw new IllegalArgumentException("Invalid page");var out=new JsonArray();db.recordPage("reports",owner==null?"":owner.toString(),page,5).forEach(j->out.add(owner==null?j:publicReport(j)));return out;}
 public JsonObject get(UUID owner,String id)throws Exception{UUID.fromString(id);var j=db.record("reports",id);if(j==null||!owner.toString().equals(Json.str(j,"uuid")))throw new IllegalArgumentException("Обращение не найдено");return publicReport(j);}
 public JsonArray list(int page)throws Exception{return list(null,page);}
 public void reply(String id,String author,String text,boolean resolved)throws Exception{db.transaction(()->{UUID.fromString(id);var j=db.record("reports",id);if(j==null)throw new IllegalArgumentException("Обращение не найдено");if(text.isBlank()||text.length()>1500)throw new IllegalArgumentException("Ответ: 1–1500 символов");j.addProperty("revision",j.get("revision").getAsLong()+1);j.addProperty("reply",text);j.addProperty("replyAuthor",author);j.addProperty("repliedAt",System.currentTimeMillis());j.addProperty("status",resolved?"resolved":"open");db.transaction(()->{db.record("reports",id,j);db.externalNotice(Json.str(j,"uuid"),"Ответ администрации на обращение",id);db.audit(author,"report reply",id);});});}
 public JsonObject submitRequest(UUID player,String name,JsonObject input,long now)throws Exception{return db.receipt(player.toString(),input,()->{String id=submit(player,name,input,now);var result=new JsonObject();result.addProperty("id",id);result.addProperty("text","Обращение отправлено");return result;});}
 public JsonObject replyRequest(String actor,String author,JsonObject input)throws Exception{return db.receipt(actor,input,()->{String id=Json.str(input,"id");var report=db.record("reports",id);if(report==null)throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Обращение не найдено");if(!input.has("revision")||input.get("revision").getAsLong()!=report.get("revision").getAsLong())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Обращение уже изменилось. Откройте его заново; ваш ответ сохранён.");reply(id,author,Json.str(input,"text"),input.get("resolved").getAsBoolean());var out=new JsonObject();out.addProperty("text","Ответ сохранён");out.add("report",db.record("reports",id));return out;});}
 public JsonObject cursor(UUID owner,String token)throws Exception{var result=db.recordCursor("reports",owner==null?"":owner.toString(),token,5);if(owner!=null){var clean=new JsonArray();for(var e:result.getAsJsonArray("entries"))clean.add(publicReport(e.getAsJsonObject()));result.add("entries",clean);}return result;}
 public JsonObject manageRequest(String actor,String name,JsonObject input)throws Exception{return db.receipt(actor,input,()->{String id=Json.str(input,"id");var report=db.record("reports",id);if(report==null)throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Обращение не найдено");if(!input.has("revision")||input.get("revision").getAsLong()!=report.get("revision").getAsLong())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Обращение изменилось. Откройте его заново");String operation=Json.str(input,"operation");switch(operation){
  case "claim" -> {String assigned=Json.opt(report,"assigned","");if(!assigned.isEmpty()&&!assigned.equals(actor))throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Обращением уже занимается другой администратор");report.addProperty("assigned",actor);report.addProperty("assignedName",name);}
  case "assign" -> {String target=Json.str(input,"target");UUID.fromString(target);report.addProperty("assigned",target);report.addProperty("assignedName",Json.str(input,"targetName"));}
  case "release" -> {if(!Json.opt(report,"assigned","").equals(actor))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Снять назначение может ответственный администратор");report.remove("assigned");report.remove("assignedName");}
  case "classify" -> {String category=Json.str(input,"category"),priority=Json.str(input,"priority");if(!Set.of("technical","player","appeal","other").contains(category)||!Set.of("low","normal","high").contains(priority))throw new IllegalArgumentException("Некорректная категория или приоритет");report.addProperty("category",category);report.addProperty("priority",priority);}
  case "note" -> {String text=Json.str(input,"text").strip();if(text.isBlank()||text.length()>1000)throw new IllegalArgumentException("Заметка: 1–1000 символов");var notes=report.has("internalNotes")?report.getAsJsonArray("internalNotes"):new JsonArray();if(notes.size()>=30)throw new IllegalArgumentException("Достигнут предел заметок");var note=new JsonObject();note.addProperty("author",name);note.addProperty("text",text);note.addProperty("at",System.currentTimeMillis());notes.add(note);report.add("internalNotes",notes);}
  default -> throw new IllegalArgumentException("Неизвестное действие обращения");}
  report.addProperty("revision",report.get("revision").getAsLong()+1);db.record("reports",id,report);db.audit(name,"report "+operation,id);var out=new JsonObject();out.addProperty("kind","result");out.addProperty("text","Сохранено");out.add("report",report);return out;});}
 private static JsonObject publicReport(JsonObject j){var clean=j.deepCopy();for(String key:List.of("internalNotes","assigned","assignedName","priority"))clean.remove(key);return clean;}
 public JsonObject dashboard()throws Exception{return db.inTransaction(()->{var result=new JsonObject();try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT count(*) FILTER(WHERE body->>'status'<>'resolved'),count(*) FILTER(WHERE body->>'status'<>'resolved' AND coalesce(body->>'assigned','')=''),count(*) FILTER(WHERE body->>'status'<>'resolved' AND body->>'priority'='high') FROM records WHERE namespace='reports'")){rs.next();result.addProperty("openReports",rs.getLong(1));result.addProperty("unassignedReports",rs.getLong(2));result.addProperty("highReports",rs.getLong(3));}var attention=new JsonArray();try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT body FROM records WHERE namespace='reports' AND body->>'status'<>'resolved' ORDER BY (body->>'priority'='high') DESC NULLS LAST,(coalesce(body->>'assigned','')='') DESC,(body->>'createdAt')::bigint ASC,id ASC LIMIT 2")){while(rs.next())attention.add(JsonParser.parseString(rs.getString(1)).getAsJsonObject());}result.add("attentionReports",attention);return result;});}
 public void prune(long now)throws Exception{db.pruneReports(now);}
}
